main:
    -
        path: home
        label: Home
        submenu:
            -
                path: bijeenkomsten
                label: Bijeenkomsten
            -
                path: '\#'
                label: Individueel
    -
        path: '\#'
        label: Gezinnen
    -
        path: '\#'
        label: Familieopstellingen
    -
        path: '\#'
        label: 'Over mij'
    -
        path: ''
        label: Blog
        submenu:
            -
                path: '\#'
                label: Tarieven
    -
        path: '\#'
        label: Evenementen
    -
        path: '\#'
        label: Contact
